services:
  neo4j:
    image: neo4j:latest
    container_name: seminariobd
    ports:
      - "7474:7474" # neo4j
      - "7687:7687" # python
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD} #dados do .env
    volumes:
      - neo4j_data:/data # persiste os dados caso o container reinicie

volumes:
  neo4j_data:
